create table user_tb (
  user_id bigint generated by default as identity,
  password varchar(100) not null,
  roles varchar(255) default 'ROLE_USER',
  username varchar(100) not null,
  primary key (user_id)
  )
    
  alter table user_tb 
    add unique (username)

insert into user_tb(username, password, roles)
  values ('test1@test.com', '$2a$10$icDnUYdx2B7tf/vVyAyGde5JS0TBEfUVUFp7V84uf82lh0EgdYZca', 'ROLE_USER')
insert into user_tb(username, password, roles)
  values ('test2@test.com', '$2a$10$icDnUYdx2B7tf/vVyAyGde5JS0TBEfUVUFp7V84uf82lh0EgdYZca', 'ROLE_USER')
insert into user_tb(username, password, roles)
  values ('test3@test.com', '$2a$10$icDnUYdx2B7tf/vVyAyGde5JS0TBEfUVUFp7V84uf82lh0EgdYZca', 'ROLE_USER')


create table board_tb (
  board_id bigint generated by default as identity,
  crt_dt timestamp,
  updt_dt timestamp,
  crt_id varchar(255),
  updt_id varchar(255),
  content clob,
  title varchar(100) not null,
  primary key (board_id)
  );

  
  insert into board_tb(title, content, crt_id, updt_id, crt_dt, updt_dt )
  values ('게시물1', '게시물1','test1@test.com','test1@test.com', now(), now();

  insert into board_tb(title, content, crt_id, updt_id, crt_dt, updt_dt )
  values ('게시물2', '게시물2','test1@test.com','test1@test.com', now(), now();
  
  insert into board_tb(title, content, crt_id, updt_id, crt_dt, updt_dt )
  values ('게시물3', '게시물3','test1@test.com','test1@test.com', now(), now();
  
  insert into board_tb(title, content, crt_id, updt_id, crt_dt, updt_dt )
  values ('게시물4', '게시물4','test1@test.com','test1@test.com', now(), now();
  
  insert into board_tb(title, content, crt_id, updt_id, crt_dt, updt_dt )
  values ('게시물5', '게시물5','test1@test.com','test1@test.com', now(), now();
  

