create table user_tb (
  user_id bigint generated by default as identity,
  password varchar(100) not null,
  roles varchar(255) default 'ROLE_USER',
  username varchar(100) not null,
  primary key (user_id)
  )
    
  alter table user_tb 
    add unique (username)

create table board_tb (
  board_id bigint generated by default as identity,
  crt_dt timestamp,
  updt_dt timestamp,
  crt_id varchar(255),
  updt_id varchar(255),
  content clob,
  title varchar(100) not null,
  primary key (board_id)
  )